# Generated by Django 5.2.4 on 2025-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_alter_review_product_review_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='Без имени', max_length=100),
        ),
    ]
